name: Deploy Qualisoft Elite to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH et Mise à jour Stratégique
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # Augmenter le timeout peut aider sur les VPS OVH lors de gros builds
          command_timeout: 30m 
          script: |
            # 1. Accès au répertoire RÉEL (On utilise /root car c'est là où tu es)
            cd /root/qualisoft-rd-2030
            
            # 2. Synchronisation du code
            git pull origin main
            
            # 3. Reconstruction (On enlève 'vitrine' car elle est dans un autre dossier)
            # On ne reconstruit que ce qui est dans ce docker-compose
            docker compose up -d --build --force-recreate frontend backend
            
            # 4. Base de données
            docker exec qualisoft-backend npx prisma migrate deploy
            
            # 5. Nettoyage
            docker image prune -af